
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app        # hot‑reload in dev
    environment:
      - PYTHONUNBUFFERED=1
    ports: ["8000:8000"]
    depends_on:
      - redis

  listener:
    build: ./backend
    command: ["python", "-u", "-m", "app.websocket_listener"]   # <- note -u
    environment:
      - PYTHONUNBUFFERED=1      # (either this or -u is enough)
    depends_on:
      - redis

  # Dev‑only front‑end
  frontend:
    working_dir: /app
    image: node:18-alpine
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports: ["5173:5173"]
    depends_on:
      - backend
